### ISSUE TITLE
Possibility to insert glyphicons in select options

### ISSUE THREAD

**Issue by heeren-cliqz** [thefrontside/emberx-select#119]
### Ember Version / Ember CLI Version:

**Ember Version:** 2.2.0
**Ember CLI Version:** 1.13.13

### Expected Behavior

Recommendation: When inserting the glyphicons inside the select options or produce other span elements, then it should reflect in the menu options.
{{#x-option value=conf}}
<span class="glyphicon glyphicon-ok "></span>
{{conf.title}}
{{/x-option}}

### Actual Behavior
No Glyphicon icon is visible.

**Comment by Robdel12** [comment]
Hi @heeren-cliqz! 

It sounds like you want something like [ember-dropkick](https://github.com/Robdel12/ember-dropkick) or select2 or ember-power-select for this. These are `<select>` replacements that allow you to do custom things with `<select>`s.  x-select is only a `<select>` element which doesn't allow images or anything in the options.

One of the main benefits to using `ember-dropkick` is it extends from x-select, so your API doesn't change very much. It uses DropKick.js as a select replacement which is fully accessibile. That's a big thing to lookout for when finding a select replacement. Usually select replacements break accessibility for those using screen readers. 

I'm going to go ahead and close this since we're never going to turn x-select into a select replacement. But feel free to comment and ask questions if you have any! :)
