### ISSUE TITLE
Add option to remove two way data binding in 2.x

### ISSUE THREAD

**Issue by Robdel12** [thefrontside/emberx-select#121]
### Version of x-select:
2.x

### Expected Behavior

To change the selected option in x-select and not mutate the underlying value without an action.

### Actual Behavior

It mutates the value of x-select without an action. 

## Description

For emberx-select v2.2.0 we would like to provide an option to remove the [two way data binding we do by default.](https://github.com/thefrontside/emberx-select/blob/master/addon/components/x-select.js#L74) This will set us up for v3.0.0 that will permantly remove two way data binding. 

### Approach

I think we can wrap a simple conditional [around this line.](https://github.com/thefrontside/emberx-select/blob/master/addon/components/x-select.js#L74)

### Testing

Since the updating of the value is already abstracted out into its own method we can stub it in tests and make sure it's being called when two way data binding is enabled. And we can also assert that it _doesn't_ get called when it's disabled. 

cc: @dgaus

**Comment by Robdel12** [comment]
@dgaus 2.2.0 has been released!

**Comment by dgaus** [comment]
I am testing the new version but it doesn't seem to work as intended. It seems that if `_this.updateValue()` is not called, the action is called with the old value instead of the new selection.

**Comment by Robdel12** [comment]
You are right, what a massive glaring bug :/ I'm sorry. I'm going to try and fix this by tonight!

**Comment by dgaus** [comment]
No worries. I did a sort of fix on https://github.com/dgaus/emberx-select/commit/50b7c334ca6e6b8027caed4c1ebacfcb3c659466 , I'm not too happy about it, but perhaps it's useful to you. 
The workflow I'm trying to achieve is:
- User changes selection
- A prompt is displayed, "are you sure?"
- If user clicks yes -> update the model and save (this is achievable)
- If user clicks no -> ignore the change (ok) and set back the selection to the original one (I don't know how to do this, since now the value is not associated with the current choice)

As a workaround I'm using model.rollbackAttributes, but I would rather do it using one-way binding.

**Comment by Robdel12** [comment]
Should actually be fixed #132!
